name: GitHub Actions Demo
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint commit
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y clang-format

      - name: Update source code
        run: make format

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Linter
          author_email: linter@mail.com
          message: 'lint source'
          add: '--all'

